### ISSUE TITLE
Error when running admin-bro

### ISSUE THREAD

**Issue by empeje** [SoftwareBrothers/admin-bro#151]
I've existing application, setup with this way

```javascript
// admin/index.js
import AdminBro from 'admin-bro';
import AdminBroExpress from 'admin-bro-expressjs';
import AdminBroSequelize from 'admin-bro-sequelizejs';
import models from '../models';

AdminBro.registerAdapter(AdminBroSequelize);

const admin = {};

admin.bootstrap = app => {
  const adminBro = new AdminBro({
    resources: Object.values(models),
    rootPath: '/admin'
  });
  admin.adminBro = adminBro;

  const router = AdminBroExpress.buildRouter(adminBro);
  admin.router = router;

  app.use(adminBro.options.rootPath, router);

  return admin;
};

export default admin;


//index.js
import app from './app';
import rest from './rest';
import admin from './admin';
import { BACKEND_PORT } from './config';
import { logger } from './utils';

rest.bootstrap(app);
admin.bootstrap(app);

app.listen(BACKEND_PORT, () => {
  logger.info('Server is running on port 3000');
});

```

When I open `localhost:3000/admin`, I got

```bash
AdminBro: bundle ready
Unhandled type: BOOLEAN
Unhandled type: BOOLEAN
Unhandled type: BOOLEAN
Unhandled type: BOOLEAN
Warning: Failed prop type: Invalid prop `resources[0].name` of type `object` supplied to `Sidebar`, expected `string`.
    in Sidebar
    in Context.Consumer
    in Connect(Sidebar)
    in section
    in Context.Consumer
    in StyledComponent
    in application__ApplicationWrapper
    in Fragment
    in App
    in Context.Consumer
    in Connect(App)
    in Context.Provider
    in Router
    in StaticRouter
    in Context.Provider
    in Context.Consumer
    in ThemeProvider
    in Context.Provider
    in Provider
Warning: Failed prop type: Invalid prop `parent.resources[0].name` of type `object` supplied to `SidebarParent`, expected `string`.
    in SidebarParent
    in Sidebar
    in Context.Consumer
    in Connect(Sidebar)
    in section
    in Context.Consumer
    in StyledComponent
    in application__ApplicationWrapper
    in Fragment
    in App
    in Context.Consumer
    in Connect(App)
    in Context.Provider
    in Router
    in StaticRouter
    in Context.Provider
    in Context.Consumer
    in ThemeProvider
    in Context.Provider
    in Provider
Warning: Failed prop type: Invalid prop `resource.name` of type `object` supplied to `SidebarResource`, expected `string`.
    in SidebarResource
    in Context.Consumer
    in withRouter(SidebarResource)
    in ul
    in Context.Consumer
    in Context.Consumer
    in StyledComponent
    in sidebar-parent__ResourcesList
    in li
    in SidebarParent
    in ul
    in section
    in section
    in aside
    in Context.Consumer
    in Context.Consumer
    in StyledComponent
    in sidebar__SidebarWrapper
    in Sidebar
    in Context.Consumer
    in Connect(Sidebar)
    in section
    in Context.Consumer
    in StyledComponent
    in application__ApplicationWrapper
    in Fragment
    in App
    in Context.Consumer
    in Connect(App)
    in Context.Provider
    in Router
    in StaticRouter
    in Context.Provider
    in Context.Consumer
    in ThemeProvider
    in Context.Provider
    in Provider
{ Invariant Violation: Objects are not valid as a React child (found: object with keys {plural, singular}). If you meant to render a collection of children, use an array instead.
    in a
    in Context.Consumer
    in Link
    in Context.Consumer
    in NavLink
    in Context.Consumer
    in Context.Consumer
    in StyledComponent
    in sidebar-resource__ResourceLink
    in li
    in SidebarResource
    in Context.Consumer
    in withRouter(SidebarResource)
    in ul
    in Context.Consumer
    in Context.Consumer
    in StyledComponent
    in sidebar-parent__ResourcesList
    in li
    in SidebarParent
    in ul
    in section
    in section
    in aside
    in Context.Consumer
    in Context.Consumer
    in StyledComponent
    in sidebar__SidebarWrapper
    in Sidebar
    in Context.Consumer
    in Connect(Sidebar)
    in section
    in Context.Consumer
    in StyledComponent
    in application__ApplicationWrapper
    in Fragment
    in App
    in Context.Consumer
    in Connect(App)
    in Context.Provider
    in Router
    in StaticRouter
    in Context.Provider
    in Context.Consumer
    in ThemeProvider
    in Context.Provider
    in Provider
    at /Users/mpj/danacita/reeba/node_modules/react/cjs/react.development.js:1145:30
    at traverseAllChildrenImpl (/Users/mpj/danacita/reeba/node_modules/react/cjs/react.development.js:1148:9)
    at traverseAllChildren (/Users/mpj/danacita/reeba/node_modules/react/cjs/react.development.js:1176:10)
    at mapIntoWithKeyPrefixInternal (/Users/mpj/danacita/reeba/node_modules/react/cjs/react.development.js:1254:3)
    at toArray (/Users/mpj/danacita/reeba/node_modules/react/cjs/react.development.js:1303:3)
    at ReactDOMServerRenderer.renderDOM (/Users/mpj/danacita/reeba/node_modules/react-dom/cjs/react-dom-server.node.development.js:3925:18)
    at ReactDOMServerRenderer.render (/Users/mpj/danacita/reeba/node_modules/react-dom/cjs/react-dom-server.node.development.js:3483:21)
    at ReactDOMServerRenderer.read (/Users/mpj/danacita/reeba/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:29)
    at renderToString (/Users/mpj/danacita/reeba/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:27)
    at html (/Users/mpj/danacita/reeba/node_modules/admin-bro/lib/frontend/layout-template.js:57:51)
    at AppController.index (/Users/mpj/danacita/reeba/node_modules/admin-bro/lib/backend/controllers/app-controller.js:14:12)
    at handler (/Users/mpj/danacita/reeba/node_modules/admin-bro-expressjs/plugin.js:56:52)
    at Layer.handle [as handle_request] (/Users/mpj/danacita/reeba/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mpj/danacita/reeba/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/mpj/danacita/reeba/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/mpj/danacita/reeba/node_modules/express/lib/router/layer.js:95:5)
    at /Users/mpj/danacita/reeba/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/mpj/danacita/reeba/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/mpj/danacita/reeba/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/Users/mpj/danacita/reeba/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/Users/mpj/danacita/reeba/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mpj/danacita/reeba/node_modules/express/lib/router/index.js:317:13) name: 'Invariant Violation' }

```

**Comment by wojtek-krysiak** [comment]
can you change `resources: Object.values(models),` to `resources: Object.values(models.sequelize.models),`

BTW when you pass entire database instead of resources is it working?

```
const adminBro = new AdminBro({
    //resources: Object.values(models),
    databases: [models],
    rootPath: '/admin'
  });
```

**Comment by empeje** [comment]
Hi @wojtek-krysiak,

I tried both your suggestion, the first one doesn't make any difference, it still fails.

However, the second one it works, what I need to do is pass sequelize instance to the `databases` options as a member of an array.

```diff
const adminBro = new AdminBro({
-    resources: Object.values(models),
+    databases: [sequelize],
    rootPath: '/admin'
  });
```

**Comment by wojtek-krysiak** [comment]
closing this one - added #153. And I am working on it right now.

**Comment by wojtek-krysiak** [comment]
I know what your error is: `Object.values(models)` returns not just models - it also returns `Sequelize` database object - and this causes an error. Simply pass models one by one. I updated the docs: https://softwarebrothers.github.io/admin-bro-dev/module-admin-bro-sequelizejs.html

**Comment by empeje** [comment]
NIce info @wojtek-krysiak, thanks for your help.
