### ISSUE TITLE
Logout TypeError

### ISSUE THREAD

**Issue by JanChodorowski** [SoftwareBrothers/admin-bro#163]
With:
```
"admin-bro": "^1.3.1",
"admin-bro-expressjs": "^0.2.0",
"admin-bro-mongoose": "^0.3.0",
```

The authenticated router that is set up as follows:
```
router: AdminBroExpress.buildAuthenticatedRouter(adminBro, {
    authenticate: async (email, password) => {
      if (ADMIN.password === password && ADMIN.email === email) {
        return ADMIN;
      }
      return null;
    },
    cookieName: 'adminbro',
    cookiePassword: 'somepassword',
  })
```

when trying to logout throws TypeError:

```
(node:58340) UnhandledPromiseRejectionWarning: TypeError: req.session.destroy is not a function
    at router.get (/Users/janchodorowski/test/node_modules/admin-bro-expressjs/plugin.js:174:17)
    at Layer.handle [as handle_request] (/Users/janchodorowski/test/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/janchodorowski/test/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/janchodorowski/test/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/janchodorowski/test/node_modules/express/lib/router/layer.js:95:5)
    at /Users/janchodorowski/test/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/janchodorowski/test/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/janchodorowski/test/node_modules/express/lib/router/index.js:275:10)
    at router.use (/Users/janchodorowski/test/node_modules/admin-bro-expressjs/plugin.js:167:7)
    at Layer.handle [as handle_request] (/Users/janchodorowski/test/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/janchodorowski/test/node_modules/express/lib/router/index.js:317:13)
    at /Users/janchodorowski/test/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/janchodorowski/test/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/janchodorowski/test/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/Users/janchodorowski/test/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/Users/janchodorowski/test/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by Chukstart** [comment]
I also got this error because I am using **cookie-session** and admin bro uses express session so I could not initialize them both I don't know why I did not research much but for a work around you could open the file **/Users/janchodorowski/test/node_modules/admin-bro-expressjs/plugin.js:174:17**
and substitute that `req.session.destroy `with  `req.session.adminUser = null; `That was my work around

**Comment by JanChodorowski** [comment]
My working workaround is to mount AdminBro middleware (with express-session) before cookie-session middleware.  Like so:

```
app.use(adminBro.config.options.rootPath, adminBro.router);
app.use(
  cookieSession({ maxAge: 30 * 24 * 60 * 60 * 1000, keys: [keys.cookieKey] })
);
```

The other way around gives the error from the original post.
