### ISSUE TITLE
AdminBro UI cannot INSERT/UPDATE when PrimaryKey is not id. 

### ISSUE THREAD

**Issue by rafagarciac** [SoftwareBrothers/admin-bro#204]
> Sequelize CLI [Node: 11.2.0, CLI: 5.5.1, ORM: 5.19.6]
- I created a new model called `country` and put as PrimaryKey `code` CHAR(2) type column.
```js
'use strict';

module.exports = (sequelize, DataTypes) => {
  const Country = sequelize.define('Country', {
    code: { type: DataTypes.CHAR(2), primaryKey: true, allowNull: false, defaultValue: '' },
    name: { type: DataTypes.STRING(100), allowNull: false, defaultValue: '' },
  }, {
    modelName: 'Country',
    timestamps: false,
    freezeTableName: true,
    tableName: 'country',
    sequelize,
  });
  Country.associate = function (models) {
    // associations can be defined here
  };
  return Country;
};
```
- After doing all the migrations and migrate successfully I tried to create a new Country from AdminBro and then I got the following exception:

```sql
Executing (default): UPDATE `country` SET `name`=?,`code`=? WHERE `id` = ?
{ SequelizeDatabaseError: Unknown column 'id' in 'where clause'
    at Query.formatError (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at handler (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Prepare.Commands.Prepare [as onResult] (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/connection.js:595:11)
    at Prepare.execute (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/connection.js:408:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/connection.js:70:12)
    at PacketParser.executeStart (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/connection.js:77:25)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)
From previous event:
    at Query.run (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/sequelize/lib/dialects/mysql/query.js:39:12)
    at runHooks.then.then (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/sequelize/lib/sequelize.js:645:29)
From previous event:
    at Promise.try.then.connection (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/sequelize/lib/sequelize.js:645:12)
From previous event:
    at Promise.resolve.retry (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/sequelize/lib/sequelize.js:641:10)
    at /home/rafa/Desktop/Crocurl/crocurl-api/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/retry-as-promised/index.js:60:10)
    at Promise.try (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/sequelize/lib/sequelize.js:631:30)
From previous event:
    at Sequelize.query (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/sequelize/lib/sequelize.js:580:23)
    at QueryInterface.bulkUpdate (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/sequelize/lib/query-interface.js:1044:27)
    at Promise.try.then.then.then.results (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/sequelize/lib/model.js:3221:34)
    at processImmediate (timers.js:632:19)
From previous event:
    at Function.update (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/sequelize/lib/model.js:3202:8)
    at Resource.update (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/admin-bro-sequelizejs/src/resource.js:122:33)
    at BaseRecord.save (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/admin-bro/lib/backend/adapters/base-record.js:141:43)
    at Object.handler (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/admin-bro/lib/backend/actions/new-action.js:35:29)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  name: 'SequelizeDatabaseError',
  parent:
   { Error: Unknown column 'id' in 'where clause'
       at Packet.asError (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/packets/packet.js:708:17)
       at Prepare.execute (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/commands/command.js:28:26)
       at Connection.handlePacket (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/connection.js:408:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/connection.js:70:12)
       at PacketParser.executeStart (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/connection.js:77:25)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:287:12)
       at readableAddChunk (_stream_readable.js:268:11)
       at Socket.Readable.push (_stream_readable.js:223:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)
     code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlState: '42S22',
     sqlMessage: "Unknown column 'id' in 'where clause'",
     sql: 'UPDATE `country` SET `name`=?,`code`=? WHERE `id` = ?',
     parameters: [ 'Bulgary', 'LL', 'LL' ] },
  original:
   { Error: Unknown column 'id' in 'where clause'
       at Packet.asError (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/packets/packet.js:708:17)
       at Prepare.execute (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/commands/command.js:28:26)
       at Connection.handlePacket (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/connection.js:408:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/connection.js:70:12)
       at PacketParser.executeStart (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (/home/rafa/Desktop/Crocurl/crocurl-api/node_modules/mysql2/lib/connection.js:77:25)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:287:12)
       at readableAddChunk (_stream_readable.js:268:11)
       at Socket.Readable.push (_stream_readable.js:223:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)
     code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlState: '42S22',
     sqlMessage: "Unknown column 'id' in 'where clause'",
     sql: 'UPDATE `country` SET `name`=?,`code`=? WHERE `id` = ?',
     parameters: [ 'Bulgary', 'LL', 'LL' ] },
  sql: 'UPDATE `country` SET `name`=?,`code`=? WHERE `id` = ?',
  parameters: [ 'Bulgary', 'LL', 'LL' ] }
```

> I don't understand why is trying to perform an `UPDATE` operation when it should perform a `INSERT` operation. Thank you ! If you need more information comment to fix this ASAP ;D

**Comment by wojtek-krysiak** [comment]
fixed in the latest
