### ISSUE TITLE
Trying to add a sequelize db as a databases, TypeError: Cannot read property 'name' of undefined     at ResourceDecorator.getParent (/projects/artlex/artlex_website/backend/node_modules/admin-bro/lib/backend/decorators/resource-decorator.js:175:25) 

### ISSUE THREAD

**Issue by stalteri** [SoftwareBrothers/admin-bro#205]
I got an issue trying to add a Sequelize db as a database,

The error is:
`TypeError: Cannot read property 'name' of undefined
    at ResourceDecorator.getParent (/projects/artlex/artlex_website/backend/node_modules/admin-bro/lib/backend/decorators/resource-decorator.js:175:25)
    at ResourceDecorator.toJSON (/projects/artlex/artlex_website/backend/node_modules/admin-bro/lib/backend/decorators/resource-decorator.js:301:20)
    at store.dispatch.admin.resources.map.r (/projects/artlex/artlex_website/backend/node_modules/admin-bro/lib/frontend/store/index.js:20:27)
    at Array.map (<anonymous>)
    at initializeStore (/projects/artlex/artlex_website/backend/node_modules/admin-bro/lib/frontend/store/index.js:18:66)
    at html (/projects/artlex/artlex_website/backend/node_modules/admin-bro/lib/frontend/layout-template.js:36:36)
    at AppController.index (/projects/artlex/artlex_website/backend/node_modules/admin-bro/lib/backend/controllers/app-controller.js:27:40)
    at handler (/projects/artlex/artlex_website/backend/node_modules/admin-bro-expressjs/plugin.js:54:52)
    at Layer.handle [as handle_request] (/projects/artlex/artlex_website/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/projects/artlex/artlex_website/backend/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/projects/artlex/artlex_website/backend/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/projects/artlex/artlex_website/backend/node_modules/express/lib/router/layer.js:95:5)
    at /projects/artlex/artlex_website/backend/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/projects/artlex/artlex_website/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/projects/artlex/artlex_website/backend/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/projects/artlex/artlex_website/backend/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/projects/artlex/artlex_website/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/projects/artlex/artlex_website/backend/node_modules/express/lib/router/index.js:317:13)
    at /projects/artlex/artlex_website/backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/projects/artlex/artlex_website/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/projects/artlex/artlex_website/backend/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/projects/artlex/artlex_website/backend/node_modules/body-parser/lib/types/json.js:110:7)`
Any help would be appreciated.

**Comment by wojtek-krysiak** [comment]
can you write how you initialize adminbro and witch version of sequelize do you use

**Comment by stalteri** [comment]
> can you write how you initialize adminbro and witch version of sequelize do you use

**adminbro initialize**: 
```
const AdminBro = require('admin-bro')
const AdminBroExpress = require('admin-bro-expressjs')
const AdminBroSequelize = require('admin-bro-sequelizejs')

AdminBro.registerAdapter(AdminBroSequelize)

const { models, sequelize } = require('../db/index')

const adminBro = new AdminBro({
  databases: [sequelize],
  rootPath: '/admin',
})

const router = AdminBroExpress.buildRouter(adminBro)

module.exports = router
```

sequelize version: "^4.42.0",
**sequelize initialize:**

```
const Sequelize = require('sequelize')
const sqlite3 = require('sqlite3').verbose();
const config = require('config')
const fs = require('fs')
const path = require('path')

const seeder = require('./seeder')
const associations = require('./associations')

const directory = path.join(__dirname, '/models/')

const models = {}

// Setup sequelize
const sequelize = new Sequelize(
  config.get('options.db.name'),
  config.get('options.db.username'),
  config.get('options.db.password'),
  {
    host: config.get('options.db.host'),
    dialect: 'sqlite',
    freezeTableName: true,
    operatorsAliases: false,
    timestamps: true,
    underscored: true,
    pool: {
      maxConnections: 5,
      maxIdleTime: 30
    },
    define: {
      timestamps: true,
      createdAt: 'createdAt',
      updatedAt: 'updatedAt',
      underscored: false,
      freezeTableName: true
    },
    typeValidation: true,
    benchmark: false,
    logging: false,
    syncOnAssociation: false,
    dialectOptions: {
      encrypt: true,
    },
    storage: '/projects/artlex/artlex_website/backend/db/sqlite_db/artlex_db.sqlite'
  }
)

// Import models
fs.readdirSync(directory).forEach(file => {
  const name = file.replace('.js', '')
  models[name] = sequelize.import(directory + file)
})

// Setup model associations
associations.associate(models)

// Test connection
sequelize
  .authenticate()
  .then(() => {
    // Sync DB schema
    sequelize
      .sync({
        logging: false
      })
      .then(() => {
        seeder.seed(models, () => {
          console.log('[sequelize] database synced\n')
        })
      })
      .catch(err => {
        console.log(`\n${err.message}\n${err.stack}\n`)
      })
  })
  .catch(err => {
    console.log(`\n${err.message}\n${err.stack}\n`)
  })

module.exports = {
  models,
  sequelize,
}
```

**Comment by asdelatoile** [comment]
I had the same problem. You need to make sure you have a database name. If you use sqlite, add the attribute "database" in the config file.
