### ISSUE TITLE
Error using a custom component

### ISSUE THREAD

**Issue by haythamlabrini** [SoftwareBrothers/admin-bro#255]
Hi, 
Really liking this admin dashboard!

I am using the last beta (`1.6.3.beta`)

I am trying to get a custom component to work. It literally does nothing.

## component:
```
import React from 'react'
import { PropertyInShow } from 'admin-bro'

export default function Component({property, record}) {
  const value = record.params[property.name]
  return (<PropertyInShow property={property}>
    {value}
  </PropertyInShow>)
}
```
which is transpiled to 
```
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importDefault(require("react"));
const admin_bro_1 = require("admin-bro");
function Component({ property, record }) {
    const value = record.params[property.name];
    return (<admin_bro_1.PropertyInShow property={property}>
    {value}
  </admin_bro_1.PropertyInShow>);
}
exports.default = Component;
```
## .entry.js content:
```
AdminBro.UserComponents = {}
import Component1 from '../build/adminDashboard/components/simple-custom-component'
AdminBro.UserComponents.Component1 = Component1
```

## Error
```
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
{ Error: 'default' is not exported by build/adminDashboard/components/simple-custom-component.jsx
    at error (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:5365:30)
    at Module.error (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:9708:9)
    at handleMissingExport (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:9625:21)
    at Module.traceVariable (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:10018:17)
    at ModuleScope.findVariable (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:8685:39)
    at Identifier$1.bind (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:4394:40)
    at AssignmentExpression.bind (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:3143:23)
    at AssignmentExpression.bind (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:6180:15)
    at ExpressionStatement$1.bind (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:3143:23)
    at Program$1.bind (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:3139:31)
    at Module.bindReferences (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:9680:18)
    at Graph.link (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:13216:20)
    at Promise.all.then (/Users/haytham/Documents/projects/dancehub.io/backend/node_modules/rollup/dist/rollup.js:13073:18)
  code: 'MISSING_EXPORT',
  url:
   'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  pos: 37,
  loc:
   { column: 7,
     file:
      '/Users/haytham/Documents/projects/dancehub.io/backend/.adminbro/.entry.js',
     line: 2 },
  frame:
   '1: AdminBro.UserComponents = {}\n2: import Component1 from \'../build/adminDashboard/components/simple-custom-component\'\n          ^\n3: AdminBro.UserComponents.Component1 = Component1\n4: import Component2 from \'../build/adminDashboard/components/show-list-string-component\'',
  watchFiles:
   [ '/Users/haytham/Documents/projects/dancehub.io/backend/.adminbro/.entry.js',
     '/Users/haytham/Documents/projects/dancehub.io/backend/build/adminDashboard/components/simple-custom-component.jsx',
     '/Users/haytham/Documents/projects/dancehub.io/backend/build/adminDashboard/components/show-list-string-component.jsx' ] }
```

Do you have any idea where to start debugging?

It seems to be working using `node-ts`. I does build using tsc, but whenever I try to access the resource (login into the dashboard), it just hangs.

**Comment by wojtek-krysiak** [comment]
it might be a rollup issue (we use it for bundling). Please try to rewrite your component like this

```
import React from 'react'
import { PropertyInShow } from 'admin-bro'

const Component = ({property, record}) => {
  const value = record.params[property.name]
  return (<PropertyInShow property={property}>
    {value}
  </PropertyInShow>)
}

export default Component
```

and let me know.

**Comment by wojtek-krysiak** [comment]
aaa. and point AdminBro.bundle to your src folder instead of build.

**Comment by haythamlabrini** [comment]
Thanks! 

The file change did not change it, I was doing that at the beginning.

How would I point the AdminBro.bundle to `src`?

**Comment by wojtek-krysiak** [comment]
in the AdminBroOptions (where you create AdminBro instance) you are passing the component by using AdminBro.bundle method like this (I assume):

```
new AdminBro({
  resources: [{
      resource: YourResource,
      options: {
        ...,
        properties: {
           yourProperty: {
              components: {
                  list: AdminBro.bundle(pathToYourComponent)
              }
           }
        }
      }
  }]
})
```

so in `pathToYourComponent` just set the path to `src/....` instead of 'build/..'

**Comment by haythamlabrini** [comment]
Hey!

I am using the relative path, and the "npm run start" rewrites the `.entry.js` file.
```
show: AdminBro.bundle('../../components/simple-custom-component'),
```

Does it work on your side though? Would you be able to try something like this?

**Comment by wojtek-krysiak** [comment]
hehe - this will be a fix:

`show: AdminBro.bundle('../../../src/components/simple-custom-component')`

or whatever number of `../` you have to add in front to get to the root scope of your app where is a `src` dir.

**Comment by haythamlabrini** [comment]
Sneaky but Good call!

**Comment by Yedidyar** [comment]
I still have this problem with rollup

Any insights? 

My version
adminJs: 5.2.1

**Comment by semyonpukhovgeo** [comment]
> I still have this problem with rollup
> 
> Any insights?
> 
> My version adminJs: 5.2.1
> 
> I am using typescript. This problem appeares just on build mode.

same here. adminJs version "6.1.1" locally all works perfect, but in prod mode see error like component is undefined.
AdminJS.UserComponents always empty object on prod and request to /assets/components.bundle.js throw 404. looks like it not generated during production build
