### ISSUE TITLE
Errors running in a docker container

### ISSUE THREAD

**Issue by webface** [SoftwareBrothers/admin-bro#277]
I'm trying to dockerize my app which is bundled with admin bro. My backend node service always dies with this error. I am able to spin up the front end.
```
backend     | > node server.js
backend     | 
backend     | Mon, 20 Jan 2020 14:36:10 GMT express-session deprecated undefined resave option; provide resave option at node_modules/admin-bro-expressjs/plugin.js:138:14
backend     | Mon, 20 Jan 2020 14:36:10 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at node_modules/admin-bro-expressjs/plugin.js:138:14
backend     | AdminBro: bundle ready
backend     | (node:19) UnhandledPromiseRejectionWarning: MongooseTimeoutError: Server selection timed out after 30000 ms
backend     |     at new MongooseTimeoutError (/backend/node_modules/mongoose/lib/error/timeout.js:22:11)
backend     |     at NativeConnection.Connection.openUri (/backend/node_modules/mongoose/lib/connection.js:763:19)
backend     |     at Mongoose.connect (/backend/node_modules/mongoose/lib/index.js:332:15)
backend     |     at run (/backend/server.js:188:18)
backend     |     at Object.<anonymous> (/backend/server.js:194:1)
backend     |     at Module._compile (internal/modules/cjs/loader.js:1144:30)
backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
backend     |     at Module.load (internal/modules/cjs/loader.js:993:32)
backend     |     at Function.Module._load (internal/modules/cjs/loader.js:892:14)
backend     |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
backend     |     at internal/main/run_main_module.js:17:47
backend     | (node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
backend     | (node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
backend exited with code 0```

**Comment by webface** [comment]
I forgot to change  to `'mongodb://database:27017/mongo-auth'`
