### ISSUE TITLE
Production Auth Problem

### ISSUE THREAD

**Issue by webface** [SoftwareBrothers/admin-bro#278]
Thanks for admin bro. I'm using the software locally for a project and it works great. But when I dockerize and deploy to production, I cannot login to the admin. I get an error and it times out into a 504 page
```
TypeError: Cannot read property 'param' of undefined
    at Object.isAccessible (/backend/server.js:132:46)
    at ActionDecorator.is (/backend/node_modules/admin-bro/lib/backend/decorators/action-decorator.js:113:35)
    at ActionDecorator.isAccessible (/backend/node_modules/admin-bro/lib/backend/decorators/action-decorator.js:151:17)
    at /backend/node_modules/admin-bro/lib/backend/decorators/resource-decorator.js:258:125
    at Array.filter (<anonymous>)
    at ResourceDecorator.resourceActions (/backend/node_modules/admin-bro/lib/backend/decorators/resource-decorator.js:258:40)
    at ResourceDecorator.toJSON (/backend/node_modules/admin-bro/lib/backend/decorators/resource-decorator.js:329:29)
    at /backend/node_modules/admin-bro/lib/frontend/store/index.js:24:34
    at Array.map (<anonymous>)
    at initializeStore (/backend/node_modules/admin-bro/lib/frontend/store/index.js:22:66)
    at html (/backend/node_modules/admin-bro/lib/frontend/layout-template.js:36:36)
    at AppController.index (/backend/node_modules/admin-bro/lib/backend/controllers/app-controller.js:27:40)
    at handler (/backend/node_modules/admin-bro-expressjs/plugin.js:56:52)
    at Layer.handle [as handle_request] (/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/backend/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/backend/node_modules/express/lib/router/route.js:112:3)
```
The issue is with
```
const canEditEntry = ({ currentAdmin, record }) => {
  return currentAdmin && (
    currentAdmin.role === 'admin'
    || currentAdmin._id === record.param('ownerId')
  )
}
```
It appears record is undefined
Here is my set up
```
const express = require('express');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const mongoose = require('mongoose');
const AdminBro = require('admin-bro');
const AdminBroExpress = require('admin-bro-expressjs');
const AdminBroMongoose = require('admin-bro-mongoose');
const bcrypt = require('bcryptjs');
const session = require('express-session');

const { getSecret } = require('./auth/secrets');
const usersRoute = require('./auth/routes/users');
const blogsRoute = require('./auth/routes/blogs');

if (process.env.NODE_ENV !== 'production') {
	require('dotenv').config();
}
AdminBro.registerAdapter(AdminBroMongoose);
mongoose.Promise = global.Promise;
mongoose.set('useNewUrlParser', true);
mongoose.set('useFindAndModify', false);
mongoose.set('useCreateIndex', true);
mongoose.set('useUnifiedTopology', true);

const User = require('./auth/models/user');
const Blog = require('./auth/models/blog');
const Page = require('./auth/models/page');

const app = express();
const port = process.env.PORT || 3001;
app.use(express.static('./public'));

//app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(cookieParser());
const sess = {
  secret: 'tranquility-bay',
  cookie: {},
  resave: true,
  saveUninitialized: true
}

if (app.get('env') === 'production') {
  app.set('trust proxy', 1) // trust first proxy
  sess.cookie.secure = true // serve secure cookies
}
// RBAC functions
const canEditEntry = ({ currentAdmin, record }) => {
  return currentAdmin && (
    currentAdmin.role === 'admin'
    || currentAdmin._id === record.param('ownerId')
  )
}
const canModifyUsers = ({ currentAdmin }) => currentAdmin && currentAdmin.role === 'admin';
const adminBro = new AdminBro({
  resources: [{
    resource:User,
    options: {
      properties: {
        encryptedPassword: { isVisible: false },
        password: {
          type: 'string',
          isVisible: {
            list: false, edit: true, filter: false, show: false,
          },
        },
      },
      actions: {
        new: {
          isAccessible: canModifyUsers , 
          label : "Create new User",
          before: async (request) => {
            console.log(request);
            if(request.payload.password) {
              request.payload = {
                ...request.payload,
                encryptedPassword: await bcrypt.hash(request.payload.password, 10),
                password: undefined,
              }
            }
            return request
          },
        },
        edit: {
          isAccessible: canModifyUsers ,
          label:'Change this Mofo',
          before: async (request) => {
            console.log(request);
            if(request.payload.password) {
              request.payload = {
                ...request.payload,
                encryptedPassword: await bcrypt.hash(request.payload.password, 10),
                password: undefined,
              }
            }
            return request
          },
        },
        delete: { isAccessible: canModifyUsers },
      }
    }
  
  },{
    resource:Page,
    options: {
      properties: {
        ownerId: { isVisible: { edit: false, show: true, list: true, filter: true } },
        body: { type: 'richtext' },
        'features.body': { type: 'richtext' },
        'features.id':{
          isVisible: {
            list: false, edit: false, filter: false, show: false,
          }
        }
      },
      actions: {
        edit: { isAccessible: canEditEntry },
        delete: { isAccessible: canEditEntry },
        new: {
          isAccessible: canEditEntry,
          label: 'Create new Page',
          before: async (request, { currentAdmin }) => {
            request.payload.record = {
              ...request.payload.record,
              ownerId: currentAdmin._id,
            }
            return request
          },
        }
      }
    }
  },{
    resource:Blog,
    options: {
      properties: {
        ownerId: { isVisible: { edit: false, show: true, list: true, filter: true } },
        body: { type: 'richtext' }
      },
      actions: {
        edit: { isAccessible: canEditEntry },
        delete: { isAccessible: canEditEntry },
        new: {
          isAccessible: canEditEntry,
          label: 'Create new Post',
          before: async (request, { currentAdmin }) => {
            request.payload.record = {
              ...request.payload.record,
              ownerId: currentAdmin._id,
            }
            return request
          },
        }
      }
    }
  }],
  rootPath: '/',
  branding: {
    logo: 'https://www.mysite.com/img/logo-mini.png',
    companyName: 'ME',
    softwareBrothers: false   
  },
  dashboard: {
    handler: async () => {

    },
    component: AdminBro.bundle('./dashboard')
  },
})

const router = AdminBroExpress.buildAuthenticatedRouter(adminBro, {
  authenticate: async (email, password) => {
    const user = await User.findOne({ email })
    if (user) {
      const matched = await bcrypt.compare(password, user.encryptedPassword)
      if (matched) {
        return user
      }
    }
    return false
  },
  cookiePassword: 'some-secret-password-used-to-secure-cookie',
})
//app.use(session(sess));
app.use('/api/users', usersRoute);
app.use('/api/blogs', blogsRoute);
app.use(adminBro.options.rootPath, router);
const run = async () => {
  await mongoose.connect(getSecret('dbUri'),
  { useNewUrlParser: true, useUnifiedTopology: true })
  app.listen(port, () => {
    console.log(`Server running on port ${port}`)
  })
}
run()
```

**Comment by kiminohero** [comment]
I guess it's record.params

**Comment by webface** [comment]
I'm using the example from the documentation. How do I avoid this?

**Comment by kiminohero** [comment]
Instead of destructuring in the arguement try console logging the arguement itself. See what adminbro passing into the function. You might figure out from there.

**Comment by wojtek-krysiak** [comment]
try to move new AdminBro(...) to the async function after the mongoose.connect invocation

**Comment by webface** [comment]
> Instead of destructuring in the arguement try console logging the arguement itself. See what adminbro passing into the function. You might figure out from there.

@kiminohero I did that and noticed admin bro passes an undefined record object when you log in thats actually populated when navigating resources so this fixed it
```const canEditEntry = ({ currentAdmin, record }) => {
	return currentAdmin && (
	  currentAdmin.role === 'admin'
	  || (record !== undefined) ? currentAdmin._id === record.param('ownerId') : true
	)
  }
```
@kiminohero @wojtek-krysiak I'd love to help update your documentation. I'm working on an example app that is more correct

**Comment by webface** [comment]
Can you please quickly advise me on this problem? https://github.com/SoftwareBrothers/admin-bro/issues/308
👍 @kiminohero

**Comment by webface** [comment]
Sorry still not fixed

**Comment by webface** [comment]
```
const canEditEntry = ({ currentAdmin, record }) => {
	let conditions = [
		typeof record !== "undefined" && currentAdmin._id === record.param('ownerId')
	]
	return currentAdmin && (
	  currentAdmin.role === 'admin'
	  || conditions.indexOf(false) === -1
	)
}
```

**Comment by webface** [comment]
```
const canEditEntry = ({ currentAdmin, record }) => {
	return currentAdmin && (
	  currentAdmin.role === 'admin'
	  || (typeof record !== "undefined" && currentAdmin._id === record.param('ownerId'))
	)
}
```
