### ISSUE TITLE
Cannot update mongoose

### ISSUE THREAD

**Issue by emrahc** [SoftwareBrothers/admin-bro#280]
I use mongo-atlas
I added admin bro to my nodejs application like in documents.  Sometimes i cant see fields. Error message is ;

```
Error: There are no resources with given id: "User"
[0] This is the list of all registered resources you can use:
[0] user, profile, post
[0]     at AdminBro.findResource (/home/emrah/Belgeler/devconnect/node_modules/admin-bro/lib/admin-bro.js:251:13)
[0]     at PropertyDecorator.reference (/home/emrah/Belgeler/devconnect/node_modules/admin-bro/lib/backend/decorators/property-decorator.js:90:36)
[0]     at /home/emrah/Belgeler/devconnect/node_modules/admin-bro/lib/backend/utils/populator.js:25:57
[0]     at Array.filter (<anonymous>)
[0]     at populator (/home/emrah/Belgeler/devconnect/node_modules/admin-bro/lib/backend/utils/populator.js:25:41)
[0]     at ApiController.recordAction (/home/emrah/Belgeler/devconnect/node_modules/admin-bro/lib/backend/controllers/api-controller.js:194:45)
[0]     at processTicksAndRejections (internal/process/task_queues.js:94:5)
[0]     at async handler (/home/emrah/Belgeler/devconnect/node_modules/admin-bro-expressjs/plugin.js:56:22)
```
When i can see the field, i try to update than get this error message

```
 Error: There are no resources with given id: "users"
[0] This is the list of all registered resources you can use:
[0] user, profile, post
[0]     at AdminBro.findResource (/home/emrah/Belgeler/devconnect/node_modules/admin-bro/lib/admin-bro.js:251:13)
[0]     at PropertyDecorator.reference (/home/emrah/Belgeler/devconnect/node_modules/admin-bro/lib/backend/decorators/property-decorator.js:90:36)
[0]     at /home/emrah/Belgeler/devconnect/node_modules/admin-bro/lib/backend/utils/populator.js:25:57
[0]     at Array.filter (<anonymous>)
[0]     at populator (/home/emrah/Belgeler/devconnect/node_modules/admin-bro/lib/backend/utils/populator.js:25:41)
[0]     at ApiController.recordAction (/home/emrah/Belgeler/devconnect/node_modules/admin-bro/lib/backend/controllers/api-controller.js:194:45)
[0]     at processTicksAndRejections (internal/process/task_queues.js:94:5)
[0]     at async handler (/home/emrah/Belgeler/devconnect/node_modules/admin-bro-expressjs/plugin.js:56:22)
```
User schema

```
const mongoose = require("mongoose");
const { ObjectId } = mongoose.Schema;
const UserSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  email: {
    type: String,
    required: true,
    unique: true
  },
  password: {
    type: String,
    required: true
  },
  approved: {
    type: Boolean,
    required: true,
    default: false
  },
  payment: {
    type: Boolean,
    default: false
  },
  paymentDate: {
    type: Date
  },
  resetToken: String,
  resetTokenExpiration: Date,
  following: [{ type: ObjectId, ref: "User" }],
  followers: [{ type: ObjectId, ref: "User" }],
  role: {
    type: String,
    required: true,
    default: "user",
    enum: ["user", "admin", "root", "commission"]
  },
  date: {
    type: Date,
    default: Date.now
  }
});

module.exports = User = mongoose.model("user", UserSchema);
```

Profile schema

```
const mongoose = require("mongoose");

const ProfileSchema = new mongoose.Schema({
	user: {
		type: mongoose.Schema.Types.ObjectId,
		ref: "user"
	},
	image: {
		type: String
	},
	company: {
		type: String
	},
	website: {
		type: String
	},
	start:{
		type:Number,
		required:true
	},
	graduation:{
		type:Number,
		required:true
	},
	option:{
		type:String,
		required:true
	},
	mentorship:{
		type:Boolean,
		default:false
	},
	scholarship:{
		type:Boolean,
		default:false
	},
	representative:{
		type:Boolean,
		default:false
	},
	location: {
		type: String
	},
	status: {
		type: String,
		required: true
	},
	skills: {
		type: [String],
		required: true
	},
	bio: {
		type: String
	},
	description:{
		type:String
	},
	experience: [
		{
			title: {
				type: String,
				required: true
			},
			company: {
				type: String,
				required: true
			},
			location: {
				type: String
			},
			from: {
				type: Date,
				required: true
			},
			to: {
				type: Date
			},
			current: {
				type: Boolean,
				default: false
			},
			description: {
				type: String
			}
		}
	],
	education: [
		{
			school: {
				type: String,
				required: true
			},
			degree: {
				type: String,
				required: true
			},
			fieldofstudy: {
				type: String,
				required: true
			},
			from: {
				type: Date,
				required: true
			},
			to: {
				type: Date
			},
			current: {
				type: Boolean,
				default: false
			},
			description: {
				type: String
			}
		}
	],
	social: {
		youtube: {
			type: String
		},
		twitter: {
			type: String
		},
		facebook: {
			type: String
		},
		linkedin: {
			type: String
		},
		instagram: {
			type: String
		}
	},
	date: {
		type: Date,
		default: Date.now
	}
});

module.exports = Profile = mongoose.model("profile", ProfileSchema);

```

How can i solve this problem thanks.

**Comment by wojtek-krysiak** [comment]
in mongoose.model you use "user" but i ref ther is a ref: "User" (ie in followers). try to unify it and it should help.

**Comment by emrahc** [comment]
I changed  ref's in followers and following as you suggested. But still can't update fields.
Errors in termina;
@wojtek-krysiak 
```
Error: Request aborted
[0]     at IncomingMessage.<anonymous> (/home/emrah/Belgeler/devconnect/node_modules/formidable/lib/incoming_form.js:122:19)
[0]     at IncomingMessage.emit (events.js:223:5)
[0]     at abortIncoming (_http_server.js:496:9)
[0]     at socketOnClose (_http_server.js:489:3)
[0]     at Socket.emit (events.js:228:7)
[0]     at TCP.<anonymous> (net.js:664:12)
[0] Error: Request aborted
[0]     at IncomingMessage.<anonymous> (/home/emrah/Belgeler/devconnect/node_modules/formidable/lib/incoming_form.js:122:19)
[0]     at IncomingMessage.emit (events.js:223:5)
[0]     at abortIncoming (_http_server.js:496:9)
[0]     at socketOnClose (_http_server.js:489:3)
[0]     at Socket.emit (events.js:228:7)
[0]     at TCP.<anonymous> (net.js:664:12)
```

**Comment by wojtek-krysiak** [comment]
check out what is send from the frontend (in Network tab in chrome inspector). Maybe it will give you some clues.

**Comment by developdeez** [comment]
Same issue I couldnt use the connection method so Im trying adding my resources.
How does it see the db?
Now that I did it this way it complains about all the Models....

@emrahc did you ever get it working?

**Comment by emrahc** [comment]
@developdeez unfortunately no. I didnt try it again since last summer. I think the problem is i added Admin-bro after all models,routes. We should add admin-bro at the beginning of the each project. Admin-bro has a potential to be standart admin panel for nodejs, like django admin.
