### ISSUE TITLE
Upload component not loading

### ISSUE THREAD

**Issue by webface** [SoftwareBrothers/admin-bro#307]
`ImageUpload.jsx`
```
import React, { useState } from 'react'
import { DropArea, PropertyInEdit, BasePropertyProps } from 'admin-bro'
import { unflatten } from 'flat'

const TJImageUpload = (props) => {
	const { property, record, onChange } = props

	const fileObject = unflatten(record.params)[property.name]

	const onUpload = (files) => {
		const newRecord = {...record}
		const [file] = files

		onChange({
			...newRecord,

			params: {
				...newRecord.params,
				file: file,
				name: file.name,
				size: file.size,
				type: file.type,
			}
		})
		event.preventDefault()
	}

	return (
		<PropertyInEdit property={property}>
			<DropArea
				fileObject={fileObject}
				onUpload={onUpload}
				propertyName={property.name}
			/>
		</PropertyInEdit>
	)
}
export default TJImageUpload;
```

handler for uploaded image 
```	
actions: {
		new: {
			after: uploadImageHandler
		},
}
```

```
const uploadImageHandler = async (response, request, context) => {	
	const { record } = context;
	const { payload } = request;
	const recordData = flat.unflatten(payload);
	// console.log(recordData)

	if (!(record.isValid() && recordData && recordData.image && recordData.image.file)) {
		return response;
	}
	
	const { file } = recordData.image;

	console.log(file)
};
```

_Originally posted by @dmitryLagoda in https://github.com/SoftwareBrothers/admin-bro/issues/95#issuecomment-586908038_

**Comment by webface** [comment]
I'm following this example code to create an image upload component but the upload jsx file deosnt load. It just renders a text field here is the relevant part of my code

```{
	  resource:Page,
	  options: {
		properties: {
		  ownerId: { isVisible: { edit: false, show: true, list: true, filter: true } },
		  body: { type: 'richtext' },
		  'features.body': { type: 'richtext' },
		  'features.id':{
			isVisible: {
			  list: false, edit: false, filter: false, show: false,
			}
		  },
		  image:{
			
			component: {
				new: AdminBro.bundle('./imageUpload')
			}
		  }
		},
		actions: {
		  edit: { isAccessible: canEditEntry },
		  delete: { isAccessible: canEditEntry },
		  new: {
			isAccessible: canEditEntry,
			label: 'Create new Page',
			before: async (request, { currentAdmin }) => {
			  request.payload.record = {
				...request.payload.record,
				ownerId: currentAdmin._id,
			  }
			  return request
			},
			after: uploadImageHandler
		  }
		}
	  }
	}```

**Comment by webface** [comment]
I figured out the issue. `components` had to be plural
```image:{
			isVisible: { edit: true, show: false, list: true, filter: false },
			components: {
				list: AdminBro.bundle('./test'),
				edit: AdminBro.bundle('./imageUpload')
			}
		  }
```
However the uploadHandler code is throwing an error
```
ReferenceError: flat is not defined
backend     |     at Object.uploadImageHandler [as after] (/app/adminbro.js:16:21)
backend     |     at ActionDecorator.handler (/app/node_modules/admin-bro/lib/backend/decorators/action-decorator.js:69:31)
backend     |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
backend     |     at async handler (/app/node_modules/admin-bro-expressjs/plugin.js:56:22)
```
