### ISSUE TITLE
request being aborted 

### ISSUE THREAD

**Issue by IbrahimShamma99** [SoftwareBrothers/admin-bro#312]
I have been trying to use admin bro but the authentication is not working 
I log in but the request is being aborted

CODE 
```const express = require('express');
const mongoose = require("mongoose");
const LocalDB = require('../config/config').LocalDB;
const {secret} = require("../config/config").secret;
const config = require("../config/config");
var isProduction = process.env.NODE_ENV === 'production';

//SECTION Build server instance
var app = express();

//SECTION Import schemas
const User = require("../User/schema");
const Project = require("../Project/schema");
//SECTION  Requiring DataBase Schemas
require("../User/schema");
require("../Project/schema");

//SECTION ADMINBRO
const AdminBro = require('admin-bro');
const AdminBroMongoose = require('admin-bro-mongoose');
const AdminBroExpressjs = require('admin-bro-expressjs');
AdminBro.registerAdapter(AdminBroMongoose);

//SECTION Connecting to MongoDB
var DB = null;
if (isProduction) {

    mongoose.connect(process.env.MONGODB_URI, {
        useUnifiedTopology: true,
        useNewUrlParser: true,
        useCreateIndex: true,
    });
} else {
    DB = mongoose.connect(LocalDB, {
        useUnifiedTopology: true,
        useNewUrlParser: true,
        useCreateIndex: true,
    }).then(()=>{

      console.log("Mongo is connected");
    }).catch(()=>{
      console.log("Failed to connect Mongo");
    });
    mongoose.set('debug', true);
};

const canEditUser = ({ currentAdmin, record }) => {

  return currentAdmin && (
    currentAdmin.role === 'admin'||
    currentAdmin._id === record.param('ownerId')

  )
};

const canModifyUsers = ({ currentAdmin }) => currentAdmin && currentAdmin.role === 'admin';
const adminBro = new AdminBro({

    resources: [
        {resource: User},
        {resource:Project,properties: {
          owner: { isVisible: { edit: false, show: true, list: true, filter: true } }
        }
        }
        ],
        database:DB,
      branding: {

        companyName: config.companyName,
      },

          rootPath: config.admin ,
          loginPath:config.adminlogin ,
          actions: {
            edit: { isAccessible: canEditUser },
            delete: { isAccessible: canEditUser },
            new: {
              before: async (request, { currentAdmin }) => {
                request.payload.record = {
                  ...request.payload.record,
                  ownerId: currentAdmin._id,
                }
                return request
              },
            },
            edit: { isAccessible: canModifyUsers },
            delete: { isAccessible: canModifyUsers },
            new: { isAccessible: canModifyUsers },    
          }
  });

router = AdminBroExpressjs.buildAuthenticatedRouter(adminBro, {
    authenticate: (email, password) => {
      console.log("EMAIL:",email)
      console.log("PASSWORD:",password)
        User.findOne({ email }).then(
            (user) => {
                if (user.validPassword(password)) {
                    console.log("if");
                    return true;
                } else {
                    console.log("else");
                    return false;
                }
            }
        ).catch(
            () => {
                console.log("catch me ");
                return false;
            });
        },
        cookieName: config.secret,
        cookiePassword: config.secret
 });

// router = buildRouter(adminBro);
app.use(adminBro.options.rootPath, router);

module.exports = app;```

THE ISSUE
`BadRequestError: request aborted
    at IncomingMessage.onAborted (/home/ibrahim/Repos/Collab-Research-Server/node_modules/admin-bro-expressjs/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:228:7)
    at abortIncoming (_http_server.js:496:9)
    at socketOnClose (_http_server.js:489:3)
    at Socket.emit (events.js:228:7)
    at TCP.<anonymous> (net.js:664:12)`

**Comment by wojtek-krysiak** [comment]
try to setup admin-bro after mongoose establishes a connection (either in .then(....) or wrap everything in an async function like it is stated in the documentation example here: 

```
const run = async () => {
  await mongoose.connect('yourconnection string', { useNewUrlParser: true })
  await app.listen(8080, () => console.log(`Example app listening on port 8080!`))
}

run()
```

also I see that you put "actions" property right in AdminBroOptions  - they should be nested withing a ResourceOptions.

**Comment by IbrahimShamma99** [comment]
I have rewritten the app and it works out eventually, thanks
