### ISSUE TITLE
before hook causing after hook to fail(help!)

### ISSUE THREAD

**Issue by webface** [SoftwareBrothers/admin-bro#337]
I am using an after upload handler for uploading files. The upload handler is in the after hook as recommended. In my action `edit` which has only an `after` handler,. the upload works just fine when im in edit mode. However in my action `new` which contains a `before` and `after` handler I get an error. Here is my resource
```
{
	  resource:Page,
	  options: {
		listProperties: ['title','image', 'body', 'date', 'hidden', 'order','ownerId'],
		properties: {
		  ownerId: { isVisible: { edit: false, show: true, list: true, filter: true } },
		  body: { type: 'richtext' },
		  'features.body': { type: 'richtext' },
		  image: {
			isVisible: { edit: true, show: true, list: true, filter: false },
			components: {
				edit: AdminBro.bundle('./components/image-view'),
				show: AdminBro.bundle('./components/image-view'),
				list: AdminBro.bundle('./components/image-in-list')		
			}
		  },
		  upload: {
			isVisible: { edit: true, show: false, list: false, filter: false },
			components: {
				edit: AdminBro.bundle('./components/imageUpload')
			}
		  }
		},
		actions: {
		  edit: { isAccessible: canEditEntry, after: uploadImageHandler},
		  delete: { isAccessible: canEditEntry },
		  new: {
			isAccessible: canEditEntry,
			label: 'Create new Page',
			before: async (request, { currentAdmin }) => {
			  request.payload = {
				...request.payload,
				ownerId: currentAdmin._id,
			  }
			  //console.log(request);
			  return request
			},
			after: uploadImageHandler
		  }
		}
	  }
	}
```
and the upload handler which works on the edit screen
```
const uploadImageHandler = async (response, request, context) => {	
	const { record } = context;
	const { payload } = request;
	const recordData = flat.unflatten(payload);

	if (!(record.isValid() && recordData && recordData.file)) {
		return response;
	}

	const { file } = recordData;
	const fileName = uuid();
	const fileType = await FileType.fromFile(file.path);
	console.log('fileType',fileType);
	const syncMv = util.promisify(mv);
	const resp = await syncMv(file.path, `public/images/${fileName}.${fileType.ext}`)
		.then(()=> {

			payload.image = `${fileName}.${fileType.ext}`;
			const updateRecord = new BaseRecord(payload, context.resource).update(payload);
			return response;
		})
		.catch(err => {throw err})
	console.log('response',resp)
	return resp; 
};
```
So when i just edit the resource the upload works
When I create a new resource and upload a file with the resource, the `before` hook causes the `after`(uploading) hook to fail with this error
```
}
backend     | (node:285) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toObject' of null
backend     |     at Resource.update (/app/node_modules/admin-bro-mongoose/src/resource.js:168:29)
backend     |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
backend     |     at async BaseRecord.update (/app/node_modules/admin-bro/lib/backend/adapters/base-record.js:109:21)
backend     | (node:285) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
backend     | (node:285) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Can you please tell me what Im doing wrong? Ive been searching documentation and issues but cannot find this use case. Thanks

**Comment by wojtek-krysiak** [comment]
first I would change:
```
const resp = await syncMv(file.path, `public/images/${fileName}.${fileType.ext}`)
		.then(()=> {

			payload.image = `${fileName}.${fileType.ext}`;
			const updateRecord = new BaseRecord(payload, context.resource).update(payload);
			return response;
		})
		.catch(err => {throw err})
```

to 

```
const resp = await syncMv(file.path, `public/images/${fileName}.${fileType.ext}`)
payload.image = `${fileName}.${fileType.ext}`;
const updateRecord = new BaseRecord(payload, context.resource).update(payload);
return response;
```

maybe this will help

if not - which line in your code causes an error? - it's not seen in the stack trace.

**Comment by webface** [comment]
@wojtek-krysiak I tried with the modified code. It still works on Edit but not on New. It deosnt show the error at any other line in the code other than:
```
backend     | fileType { ext: 'jpg', mime: 'image/jpeg' }
backend     | (node:299) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toObject' of null
backend     |     at Resource.update (/app/node_modules/admin-bro-mongoose/src/resource.js:168:29)
backend     |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
backend     |     at async BaseRecord.update (/app/node_modules/admin-bro/lib/backend/adapters/base-record.js:109:21)
backend     | (node:299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
backend     | (node:299) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by webface** [comment]
looks like the update doesnt work in the new:after scenario

**Comment by wojtek-krysiak** [comment]
yes - in update we have an existing record, in new - we don't.

So please try to replace follwing lines:

```
const image = `${fileName}.${fileType.ext}`;
const updatedRecord = await record.update({ image });
response.record.params.image = image
return response
```

**Comment by webface** [comment]
@wojtek-krysiak I salute you! It works 🥇 Admin Bro is the greatest. 💯 💯

**Comment by wojtek-krysiak** [comment]
Glad you like it :) 
regarding multiple after hooks you will have to stack them manually:

```
after:  async (res, req, context) => {
  await afterHook1(res, req, context)
  await afterHook2(res, req, context)
}
```
