### ISSUE TITLE
Cannot action records in MSSQL tables that have triggers

### ISSUE THREAD

**Issue by mjlawrence83** [SoftwareBrothers/admin-bro#399]
**Describe the bug**

I'm trying to get admin-bro to work with a pre-existing DB. A number of tables have triggers on them when records are either created, updated, or deleted.

At the moment, for a given table I'm opening an existing record, updating a field and then saving.

The GUI displays a basic error to state it was not successful, and the console shows `The target table '<table name>' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.`

**Installed libraries and their versions**

* admin-bro@2.2.4
* admin-bro-expressjs@2.0.1
* admin-bro-sequelizejs@0.4.0
* sequelize@5.21.5
* mssql@6.2.0

**To Reproduce**
1. Have an MS SQL Server DB with a table with a trigger associated.
2. Load a record from that table
3. Make a change and save

**Expected behavior**
Record should save successfully.

**Screenshots**

Due to this happening in work's codebase, there's only so much info I'm allowed to give, but here is some error output 

```
0] 19:02:19 0|  | Executing (default): UPDATE [<table name>] SET [IDAPID]=@0,[RoleName]=@1,[RoleType]=@2,[MFAScope]=@3,[GroupName]=@4,[RSAMProfile]=@5,[GroupStatus]=@6,[PrimaryOwner]=@7,[IsSophiaGroup]=@8,[SecondaryOwner]=@9,[RSAMProfileDescription]=@10,[GroupStatusDescription]=@11 OUTPUT INSERTED.* WHERE [KeyID] = @12
[0] 19:02:20 0|  | 2020-04-06 19:02:20:220  error:        The target table '<table name>' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.
[0] 19:02:20 0|  | SequelizeDatabaseError: The target table '<table name>' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.
[0] 19:02:20 0|  |     at Query.formatError (I:\development\idaportal\node_modules\sequelize\lib\dialects\mssql\query.js:314:12)
[0] 19:02:20 0|  |     at Request.connection.lib.Request [as userCallback] (I:\development\idaportal\node_modules\sequelize\lib\dialects\mssql\query.js:74:23)
[0] 19:02:20 0|  |     at Request.callback (I:\development\idaportal\node_modules\tedious\lib\request.js:56:14)
19:02:20 0|  |     at Connection.endOfMessageMarkerReceived (I:\development\idaportal\node_modules\tedious\lib\connection.js:2407:20)
[0] 19:02:20 0|  |     at Connection.dispatchEvent (I:\development\idaportal\node_modules\tedious\lib\connection.js:1279:15)
[0] 19:02:20 0|  |     at Parser.tokenStreamParser.on (I:\development\idaportal\node_modules\tedious\lib\connection.js:1072:14)
[0] 19:02:20 0|  |     at emitOne (events.js:116:13)
[0] 19:02:20 0|  |     at Parser.emit (events.js:211:7)
[0] 19:02:20 0|  |     at Parser.parser.on.token (I:\development\idaportal\node_modules\tedious\lib\token\token-stream-parser.js:37:14)
[0] 19:02:20 0|  |     at emitOne (events.js:116:13)
[0] 19:02:20 0|  |     at Parser.emit (events.js:211:7)
[0] 19:02:20 0|  |     at addChunk (I:\development\idaportal\node_modules\readable-stream\lib\_stream_readable.js:298:12)
[0] 19:02:20 0|  |     at readableAddChunk (I:\development\idaportal\node_modules\readable-stream\lib\_stream_readable.js:280:11)
[0] 19:02:20 0|  |     at Parser.Readable.push (I:\development\idaportal\node_modules\readable-stream\lib\_stream_readable.js:241:10)
[0] 19:02:20 0|  |     at Parser.Transform.push (I:\development\idaportal\node_modules\readable-stream\lib\_stream_transform.js:139:32)
[0] 19:02:20 0|  |     at Parser.afterTransform (I:\development\idaportal\node_modules\readable-stream\lib\_stream_transform.js:88:10)
[0] 19:02:20 0|  |     at Parser._transform (I:\development\idaportal\node_modules\tedious\lib\token\stream-parser.js:88:14)
[0] 19:02:20 0|  |     at Parser.Transform._read (I:\development\idaportal\node_modules\readable-stream\lib\_stream_transform.js:177:10)
[0] 19:02:20 0|  |     at Parser.Transform._write (I:\development\idaportal\node_modules\readable-stream\lib\_stream_transform.js:164:83)
[0] 19:02:20 0|  |     at doWrite (I:\development\idaportal\node_modules\readable-stream\lib\_stream_writable.js:409:139)
[0] 19:02:20 0|  |     at writeOrBuffer (I:\development\idaportal\node_modules\readable-stream\lib\_stream_writable.js:398:5)
[0] 19:02:20 0|  |     at Parser.Writable.write (I:\development\idaportal\node_modules\readable-stream\lib\_stream_writable.js:307:11)
[0] 19:02:20 0|  | From previous event:
[0] 19:02:20 0|  |     at Query._run (I:\development\idaportal\node_modules\sequelize\lib\dialects\mssql\query.js:45:12)
[0] 19:02:20 0|  |     at Promise.using.connection (I:\development\idaportal\node_modules\sequelize\lib\dialects\mssql\query.js:108:69)
[0] 19:02:20 0|  | From previous event:
[0] 19:02:20 0|  |     at Query.run (I:\development\idaportal\node_modules\sequelize\lib\dialects\mssql\query.js:108:20)
[0] 19:02:20 0|  |     at runHooks.then.then (I:\development\idaportal\node_modules\sequelize\lib\sequelize.js:645:29)
[0] 19:02:20 0|  | From previous event:
[0] 19:02:20 0|  |     at Promise.try.then.connection (I:\development\idaportal\node_modules\sequelize\lib\sequelize.js:645:12)
[0] 19:02:20 0|  | From previous event:
[0] 19:02:20 0|  |     at Promise.resolve.retry (I:\development\idaportal\node_modules\sequelize\lib\sequelize.js:641:10)
[0] 19:02:20 0|  |     at I:\development\idaportal\node_modules\retry-as-promised\index.js:70:21
[0] 19:02:20 0|  |     at new Promise (<anonymous>)
[0] 19:02:20 0|  |     at retryAsPromised (I:\development\idaportal\node_modules\retry-as-promised\index.js:60:10)
[0] 19:02:20 0|  |     at Promise.try (I:\development\idaportal\node_modules\sequelize\lib\sequelize.js:631:30)
[0] 19:02:20 0|  | From previous event:
[0] 19:02:20 0|  |     at Sequelize.query (I:\development\idaportal\node_modules\sequelize\lib\sequelize.js:580:23)
[0] 19:02:20 0|  |     at QueryInterface.bulkUpdate (I:\development\idaportal\node_modules\sequelize\lib\query-interface.js:1044:27)
[0] 19:02:20 0|  |     at Promise.try.then.then.then.results (I:\development\idaportal\node_modules\sequelize\lib\model.js:3222:34)
[0] 19:02:20 0|  |     at runCallback (timers.js:794:20)
[0] 19:02:20 0|  |     at tryOnImmediate (timers.js:752:5)
[0] 19:02:20 0|  |     at processImmediate [as _immediateCallback] (timers.js:729:5)
[0] 19:02:20 0|  | From previous event:
[0] 19:02:20 0|  |     at Function.update (I:\development\idaportal\node_modules\sequelize\lib\model.js:3203:8)
[0] 19:02:20 0|  |     at Resource.update (I:\development\idaportal\node_modules\admin-bro-sequelizejs\src\resource.js:133:33)
19:02:20 0|  |     at BaseRecord.update (I:\development\idaportal\node_modules\admin-bro\lib\backend\adapters\base-record.js:109:41)
[0] 19:02:20 0|  |     at Object.handler (I:\development\idaportal\node_modules\admin-bro\lib\backend\actions\edit-action.js:57:18)
[0] 19:02:20 0|  |     at ActionDecorator.handler (I:\development\idaportal\node_modules\admin-bro\lib\backend\decorators\action-decorator.js:74:35)
[0] 19:02:20 0|  |     at ApiController.recordAction (I:\development\idaportal\node_modules\admin-bro\lib\backend\controllers\api-controller.js:191:55)
[0] 19:02:20 0|  |     at <anonymous>
[0] 19:02:20 0|  | 2020-04-06 19:02:20:220  info:         ::ffff:127.0.0.1 /dbadmingui/api/resources/<table name>/records/1/edit POST 500 4964 347.408 ms
```

**Additional context**

Having a google about I found this: http://www.sql-server-helper.com/error-messages/msg-334.aspx

**Comment by mjlawrence83** [comment]
After stepping through all code, I believe this is down to https://github.com/sequelize/sequelize/issues/4807 and I'm using sequelize-auto to generate the models on the fly
