### ISSUE TITLE
Cant filter using nested fields

### ISSUE THREAD

**Issue by lasttry** [SoftwareBrothers/admin-bro#632]
**Describe the bug**
When trying to filter the results of the column using a nested field, i am always receiving
TypeError: Cannot read property 'type' of null
    at filter.reduce (/home/rsantos/scbraga/node_modules/@admin-bro/mongoose/src/utils/convert-filter.js:18:22)
    at Array.reduce (<anonymous>)
    at Filter.reduce (/home/rsantos/scbraga/node_modules/admin-bro/lib/backend/utils/filter.js:111:40)
    at convertFilter (/home/rsantos/scbraga/node_modules/@admin-bro/mongoose/src/utils/convert-filter.js:14:17)
    at Resource.find (/home/rsantos/scbraga/node_modules/@admin-bro/mongoose/src/resource.js:92:13)
    at Object.handler (/home/rsantos/scbraga/node_modules/admin-bro/lib/backend/actions/list-action.js:81:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Installed libraries and their versions**
    "@admin-bro/express": "^3.0.1",
    "@admin-bro/mongoose": "^1.0.0",
    "admin-bro": "^3.2.5",
    "express": "^4.17.1",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.1",
    "mongoose": "^5.10.8",
    "nodemon": "^2.0.4"

**To Reproduce**
rh.js

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var global = require('./global')


var tipoSchema = new Schema({
  type: Array,
  escalao: {
    type: String
  },
  tipo: {
    type: String,
    required: true
  }
})

var rhSchema = new Schema({
  nome: {
    type: String,
    required: true
  },
  genero: {
    type: String,
    required: true
  },
  dataNascimento: {
      type: Date
  },
  numeroIdentificacao: {
      type: Number
  },
  licenca: {
      type: Number
  },
  exameMedico: {
      type: Date
  },
  email: {
      type: String
  },
  contacto: {
      type: String
  },
  tipos:  [ tipoSchema ]
});

var _actions = {
  list: {
    before: async (request) => {
      console.log(request.query)
      return {
        ...request,
        query: {
           ...request.query,

           //'filters.tipo': 'atleta'
        }
      }
    }
  }
}

var options = {
  actions: _actions,
  parent: global.rhParent,
  filterProperties: [ 'nome', 'genero', 'tipos.tipo' ],
  properties: {
    _id: {
      isVisible: { show: false, list: false, edit: false, filter: false}
    },
    nome: {
      position: 1,
      isTitle: true,
      isRequired: true
    },
    genero: {
      position: 2,
      availableValues: [{
        value: 'masculino', 
        label: 'Masculino'
      }, {
        value: 'feminino', 
        label: 'Feminino'
      }]
    },
    dataNascimento: { position: 3 },
    numeroIdentificacao: { position: 4 },
    licenca: { position: 5 },
    exameMedico: { position: 6 },
    email: { position: 7 },
    contacto: { position: 8 },
    'tipos.escalao': {
      isVisible: { show: true, list: true, edit: true, filter: true },
      availableValues: [{ 
        value: 'u8', label: 'U8'
      }, {
        value: 'u10', label: 'U10'
      }, {
        value: 'u12', label: 'U12'
      }, {
        value: 'u14f', label: 'U14F'
      }, {
        value: 'u14m', label: 'u14M'
      }, {
        value: 'u16f', label: 'U16F'
      }, {
        value: 'u16m', label: 'U16M'
      }, {
        value: 'u18', label: 'U18'
      }, {
        value: 'u19', label: 'U19'
      }, {
        value: 'senioresf', label: 'Seniores F'
      }, {
        value: 'senioresm', label: 'Seniores M'
      }]
    },
    'tipos.tipo': {
      availableValues: [{ 
        value: 'atleta', label: 'Atleta'
      }, {
        value: 'treinador', label: 'Treinador'
      }, {
        value: 'seccionista', label: 'Seccionista'
      }, {
        value: 'director', label: 'Director'
      }]
    }
  }
}

var rh = { 
  resource: mongoose.model('rh', rhSchema), 
  options: options,
  //actions: actions
};

module.exports = { rhSchema, rh };
```

open filters, select one of the filters for the 'Tipo' and it should display all entrys that contains 'Tipo' = 'Atleta'

**Expected behavior**

The rows should be displayd

**AdminBroOptions with schema**

```
const express = require('express')
const session = require('express-session')
const { default: AdminBro } = require('admin-bro')
const mongoose = require('mongoose')
const AdminBroExpress = require('@admin-bro/express')
const AdminBroMongoose = require('@admin-bro/mongoose')

const { rh } = require('./schemas/rh')

var language = require('./schemas/languages')

AdminBro.registerAdapter(AdminBroMongoose);
const rhParent = {
  name: 'Recursos Humanos',
  icon: 'Events'
}
const AdminBroOptions = {
  resources: [ rh ],
  ...language.language,
  rootPath: '/'
}
console.log(rh)
const app = express()

const run = async () => {
  const mongooseDb = await mongoose.connect('mongodb://127.0.0.1:27017/scbraga', { useNewUrlParser: true, useUnifiedTopology: true })
  const admin = new AdminBro(
    AdminBroOptions
  )
  const router = AdminBroExpress.buildRouter(admin)

  app.use(admin.options.rootPath, router)

  app.listen(+8080, () => console.log(
    //`Example app listening at http://localhost:${APP_PORT}${APP_ROOT}`,
  ))
}
run()
```

**Desktop (please complete the following information if relevant):**
 - OS: ubuntu 20
 - Browser chrome

**Comment by wojtek-krysiak** [comment]
right now it is not supported - you will have to write your own handler for list action to manually make it work

**Comment by wojtek-krysiak** [comment]
#251 should fix that globally. So closing this one
