### ISSUE TITLE
Unexpected Identifier in login-template.js

### ISSUE THREAD

**Issue by Odisseuss** [SoftwareBrothers/admin-bro#82]
>This is the error i get after trying to start the server using "node app.js" 
:\Users\Rares\Desktop\UNI\ONE FELL SWOOP new\node_modules\admin-bro\src\frontend\login-template.js:1
(function (exports, require, module, __filename, __dirname) { import React from 'react'
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Module._compile (C:\Users\Rares\Desktop\UNI\ONE FELL SWOOP new\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.newLoader [as .js] (C:\Users\Rares\Desktop\UNI\ONE FELL SWOOP new\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Rares\Desktop\UNI\ONE FELL SWOOP new\node_modules\admin-bro\src\admin-bro.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module._compile (C:\Users\Rares\Desktop\UNI\ONE FELL SWOOP new\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)

This is the code from my app.js file

`var express = require("express"),
    app = express(),
    bodyParser = require("body-parser"),
    mongoose = require("mongoose"),
    passport = require("passport"),
    LocalStrategy = require("passport-local"),
    methodOverride = require("method-override"),
    seedDB = require("./seedDB"),
    Testimonial = require("./models/Testimonial");

//Route import
var indexRoutes = require("./routes/index");
var testimonialRoutes = require("./routes/testimonials/testimonials");
var adminRoutes = require("./routes/admin");
// var testimonials = require("./routes/testimonials");

//Database connect
mongoose.connect("mongodb://localhost/One-fell-swoop", {
    useNewUrlParser: true
});
seedDB();

app.set("view engine", "ejs");
app.use(bodyParser.urlencoded({
    extended: true
}));
app.use(express.static(__dirname + "/css"));
app.use(methodOverride("_method"));
app.use(indexRoutes);
app.use("/testimonials", testimonialRoutes);
app.use("/admin", adminRoutes);

//Port setup
var port = process.env.PORT || 3000;
app.listen(port, function () {
    console.log("Server is up");
});`

And this is the code from my admin.js file where i connected mongoose to admin-bro

`const AdminBro = require('admin-bro');
const AdminBroExpress = require('admin-bro-expressjs');

const express = require('express');
const app = express();
const mongoose = require('mongoose');

AdminBro.registerAdapter(AdminBroMongoose);

const adminBro = new AdminBro({
    databases: [mongoose],
    rootPath: '/admin',
})

const router = AdminBroExpress.buildRouter(adminBro)

module.exports = router;`

Could you help me understand what is going on?

**Comment by wojtek-krysiak** [comment]
which node version do you have? - try to update to the at least 10.x and let me know if that helped.

**Comment by Odisseuss** [comment]
Thank you for your response! i am currently running node v11.6, so i don't think that is the problem

**Comment by Odisseuss** [comment]
I installed the latest version of node, hoping that maybe it will fix the problem, but i still get the same error

**Comment by wojtek-krysiak** [comment]
It seems to be a problem related with babel. The error you have: `(function (exports, require, module, __filename, __dirname)` points to the already transcompiled file (the original file looks like this: https://github.com/SoftwareBrothers/admin-bro/blob/master/src/frontend/login-template.js#L1).

But first, can you try to launch admin with the simplest, one file, server (https://softwarebrothers.github.io/admin-bro-dev/tutorial-01-example.html) and let me know if it works. If it doesn't - maybe there is something wrong with admin-bro + windows in general.

**Comment by Odisseuss** [comment]
I created a new "server.js" file where i put the code from the example app. This time the error changed a bit:

> import React from 'react'
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Module._compile (C:\Users\Rares\Desktop\UNI\ONE FELL SWOOP new\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.newLoader [as .js] (C:\Users\Rares\Desktop\UNI\ONE FELL SWOOP new\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Rares\Desktop\UNI\ONE FELL SWOOP new\node_modules\admin-bro\src\admin-bro.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Module._compile (C:\Users\Rares\Desktop\UNI\ONE FELL SWOOP new\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.newLoader [as .js] (C:\Users\Rares\Desktop\UNI\ONE FELL SWOOP new\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)

**Comment by 404-html** [comment]
I got exactly the same problem. Like I mentioned on https://github.com/SoftwareBrothers/admin-bro/issues/84 simple file with:
```js
const AdminBro = require('admin-bro')
```
only results in the same exception being thrown. 

Don't you plan to release dist build with everything already transpiled in it?

**Comment by wojtek-krysiak** [comment]
@404-html do you use windows as well?

**Comment by 404-html** [comment]
Yes. Win10 x64.

**Comment by wojtek-krysiak** [comment]
@404-html - regarding the build - I added this to the project but before that, there are lots of other things planned. Unfortunately, I don't have windows machine now to debug that.

But you can use docker environment until this issue is closed.

**Comment by wojtek-krysiak** [comment]
@404-html, @Odisseuss - I've just added a `build` stage in the deployment. This should fix the issue. Please install the `0.9.0-beta.2` version and let me know
