### ISSUE TITLE
Filter/search: ILIKE operator not supported

### ISSUE THREAD

**Issue by periplox** [SoftwareBrothers/admin-bro#820]
**Describe the bug**
I'm having an issue that I think it's cause by [this new feature](https://github.com/SoftwareBrothers/admin-bro/issues/457). When I try to use some filters or search in the react-select component I get this error:
```
SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ILIKE '%al%') ORDER BY `Client`.`name` ASC LIMIT 0, 50' at line 1
    at Query.formatError (C:\wamp64\www\mysullair\node_modules\sequelize\lib\dialects\mysql\query.js:265:16)
    at Query.run (C:\wamp64\www\mysullair\node_modules\sequelize\lib\dialects\mysql\query.js:77:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
If I change `Op.iLike` by `Op.like` (@admin-bro/sequelize/build/utils/convert-filter.js:35) it works.

**Installed libraries and their versions**
* admin-bro@3.4.0
* admin-bro-expressjs@2.1.1
* admin-bro/sequelize@1.2.1
* mysql@8.0.22

**Expected behavior**
Maybe there could be an option to guarantee some backwards compatibility with older mysql versions.

Thanks!

**Comment by anuragmath** [comment]
I m having similar issue with the filters with admin-bro@4.0.1.
I m using mariadb with sequelize. 

As per sequelize documentation the operator Op.iLike is only available for Postgres DB.

**Comment by akshatsoni8055** [comment]
Admin bro doesn't support mysql it support postgres by default and "ILIKE" is used for postgres and mysql doesn't support "ILIKE"
mysql support "LIKE" instead of "ILIKE". so please change your database or find a substitute for adminbro

**Comment by dziraf** [comment]
@anuragmath @periplox 
`@admin-bro/sequelize@v1.3.0-beta.5` has a fix for this which basically changes `ILIKE` to `LIKE` in the SQL query because that's how it's used in TypeORM adapter. I'll try to push this change to `@adminjs/sequelize` tomorrow. `@adminjs/sequelize` will require you to change your packages to `adminjs` ones though.

**Comment by periplox** [comment]
@dziraf Hey! That would be awesome. Let me know when you push it and I'll give it a try. Thanks!
