### ISSUE TITLE
"SyntaxError: Unexpected identifier" thrown when importing admin-bro

### ISSUE THREAD

**Issue by 404-html** [SoftwareBrothers/admin-bro#84]
Running with node JS file which contains only:

```js
const AdminBro = require('admin-bro')
```

results in following exception being thrown:
```
C:\...\node_modules\admin-bro\src\frontend\login-template.js:1
(function (exports, require, module, __filename, __dirname) { import React from 'react'
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Module._compile (C:\...\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.newLoader [as .js] (C:\...\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

Looks like AdminBro front-end code is not transpiled by Babel.
I hope there's nothing wrong with my setup.

```
λ node --version
v10.15.3
```

Pozdrawiam.

**Comment by 404-html** [comment]
This is actually a duplicate with https://github.com/SoftwareBrothers/admin-bro/issues/82
