### ISSUE TITLE
Warning messages and failure to run admin-bro

### ISSUE THREAD

**Issue by Winklbauer** [SoftwareBrothers/admin-bro#89]
When I use yarn/npm to install the packages I get the following warning:

warning admin-bro > react-router-dom > react-router > create-react-context > fbjs > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

Also I am using Node v12.2.0. When I try to follow the example steps I get an error:

import React from 'react'
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Module._compile (D:\Dev\Projects\NodeJS\testAdminBro2\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.newLoader [as .js] (D:\Dev\Projects\NodeJS\testAdminBro2\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:\Dev\Projects\NodeJS\testAdminBro2\node_modules\admin-bro\src\admin-bro.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:759:30)

Can this be fixed as admin-bro is not working. I can run everything well without the admin-bro packages.

**Comment by wojtek-krysiak** [comment]
It is related to #82 - try to run this in docker for now. Next week we will try to fix it for good.

**Comment by wojtek-krysiak** [comment]
just released version `0.9.0-beta.2` which should solve this issue - please let me know if that helped

**Comment by Winklbauer** [comment]
Thank you for the fix. It works with 0.9.0-beta.2. Looking forward to the next release.
